// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmecyojlcdhkqucthrbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZWN5b2psY2Roa3F1Y3RocmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzgwMTgsImV4cCI6MjA2MDgxNDAxOH0.T_gsm7euwJugP0eiCivfw6s3cJY1Xcc_p8UoQl9qo6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);